### ISSUE TITLE
Block Design Discussion

### ISSUE THREAD

**Issue by aurooba** [helgatheviking/Simple-User-Listing#21]
Current Design: https://www.figma.com/file/H5U237OsRZ5XPY4LBxSiO6/SUL-block?node-id=0%3A1

I've definitely seen some blocks that use the pattern you've got going on in the design, where almost all of the work happens in the main editor screen in a sort of "edit" mode. However, given the type of parameters the `User Query` has, I think there's a strong argument here to put all the major settings in the Inspector and have the editor simply be the Live Preview of the shortcode.

I also think that there should probably be a separate block for multisite and single installation to start with, just to lower the complexity of the blocks and what they are trying to achieve.

Does the Figma file represent the initial settings you'd like the block to have @helgatheviking?

I'm interpreting these settings as follows:

- Display all users (default behaviour)
- Ability to custom select users
- Ability to exclude users by role

**Comment by aurooba** [comment]
I'd also suggest that instead of a search and a checklist of users:

<img width="384" alt="Screen Shot 2022-02-04 at 7 33 28 PM" src="https://user-images.githubusercontent.com/6925260/152625696-e5250aac-2752-41b7-bd3f-ab8768886f86.png">

A token multiselect control is used. It essentially works the way the `Tags` control works in the Block Editor, but as you type, it shows you a dropdown of users matching what you're typing, and then you can select, remove, etc.

![token-multi-select-control](https://user-images.githubusercontent.com/6925260/152625762-629f6be3-308c-4473-9753-d41108a67976.gif)

**Comment by helgatheviking** [comment]
👋 @aurooba 

SUL supports most of the parameters of the [`WP_User_Query`](https://developer.wordpress.org/reference/classes/wp_user_query/) class as parameters for the shortcode. 

Here's everything that currently _is_ supported:

> 'query_id' => 'simple_user_listing', // This allows for targeted filtering of pre_get_user which allows for very custom queries.
> 'role' => '', // Multiple roles can be defined in a comma separated list [userlist role="infield,outfield"]
> 'role__in' => '', // Multiple roles can be defined in a comma separated list 
> 'role__not_in' => // Multiple roles can be defined in a comma separated list
> 'include' => '', // Multiple user IDs can be defined in a comma separated list
> 'exclude' => '', // Multiple user IDs can be defined in a comma separated lis
> 'blog_id' => '',
> 'number' => get_option( 'posts_per_page', 10 ),
> 'order' => 'ASC',
> 'orderby' => 'login',
> 'meta_key' => '',
> 'meta_value' => '',
> 'meta_compare' => '=',
> 'meta_type' => 'CHAR',
> 'count_total' => true,
> 'template' => 'author' // Corresponds to content-author.php template, can accept different templates per shortcode.

Technically you can combine those to get fairly complex queries, ie: users with role "author" that have a billing address in Illinois, but I definitely think we should start as simply as possible.

The Figma is a lot incomplete, but also not a terrible starting place. I think there needs to be 2 parts.. maybe block and sidebar. The block should handy the query and the sidebar the resulting parts to be displayed

**Query**
Show all
Include specific users
Exclude specific users
Include specific roles
Exclude specific roles
Number of users (per page?)
Order/Orderby

Currently unsure if include and exclude should be mutually exclusive. If I recall.. that's what I was going for in the Figma... exclude is toggle one way and Include is the other. 

I do want it so that eventually you can build up a complex query. Technically you current can say get all Authors except Kathy and Aurooba.. which is a combo of multiple args.

There's also a possible "what should we show about each author" in the sidebar section. This might be a later phase thing though. 

**Sidebar Display**

User display name
Username vs display name vs first/last names
user avatar
link to profile page
hide/show search?

Ok that's enough thinking for today!

**Comment by aurooba** [comment]
Notes:

Initial block placeholder can show 3 options:
1. Show all users
2. Show users by x role (show dropdown of roles)
3. Select custom users.

**Comment by helgatheviking** [comment]
Ok! Latest block iteration [under development](https://github.com/helgatheviking/Simple-User-Listing/tree/features/block)

Current status: show all users in the editor using the core data store and show all users on the frontend using existing shortcode. Absolutely no UI for modifying query yet.

cc @jonathanbossenger
